from django.urls import path
from . import views

app_name = "tasks"

urlpatterns = [
    path("", views.task_list, name="task_list"),
    path("nueva/", views.task_create, name="task_create"),
    path("<int:pk>/editar/", views.task_edit, name="task_edit"),
    path("<int:pk>/eliminar/", views.task_delete, name="task_delete"),
    path("<int:pk>/hecho/", views.task_mark_done, name="task_mark_done"),
    path("<int:pk>/no-hecho/", views.task_mark_not_done, name="task_mark_not_done"),
    path("<int:pk>/caido/", views.task_mark_failed, name="task_mark_failed"),
    path("<int:pk>/deshacer/", views.task_reopen, name="task_reopen"),
    path("<int:pk>/entreno/", views.task_workout, name="task_workout"),
    path("<int:pk>/entreno/guardar/", views.task_workout_save, name="task_workout_save"),
    path("<int:pk>/entreno/guardar-manual/", views.task_workout_save_manual, name="task_workout_save_manual"),
    path("<int:pk>/entreno/circuito/<int:routine_pk>/", views.routine_play, name="routine_play"),
    path("<int:pk>/entreno/circuito/<int:routine_pk>/guardar/", views.routine_save, name="routine_save"),
    path("<int:pk>/enfoque/", views.task_focus, name="task_focus"),
    path("<int:pk>/enfoque/guardar/", views.task_focus_save, name="task_focus_save"),
    path("<int:pk>/video/", views.task_video, name="task_video"),
    path("<int:pk>/video/guardar/", views.task_video_save, name="task_video_save"),
    path("videos/nuevo/", views.saved_video_create, name="saved_video_create"),
    path("videos/<uuid:uuid>/borrar/", views.saved_video_delete, name="saved_video_delete"),
    path("planes/", views.plan_list, name="plan_list"),
    path("revision/", views.weekly_review, name="weekly_review"),
    path("<int:pk>/plan/<int:plan_pk>/", views.plan_session, name="plan_session"),
    path("<int:pk>/plan/<int:plan_pk>/guardar/", views.plan_session_save, name="plan_session_save"),
    path("planes/nuevo/", views.plan_form, name="plan_create"),
    path("planes/nuevo-ia/", views.plan_ai_form, name="plan_ai_create"),
    path("planes/<int:pk>/", views.plan_detail, name="plan_detail"),
    path("planes/<int:pk>/editar/", views.plan_form, name="plan_edit"),
    path("planes/<int:pk>/eliminar/", views.plan_delete, name="plan_delete"),
    path("planes/<int:pk>/cerrar/", views.plan_close, name="plan_close"),
    path("planes/<int:plan_pk>/objetivo/nuevo/", views.plan_item_form, name="plan_item_create"),
    path("planes/<int:plan_pk>/objetivo/<int:pk>/", views.plan_item_form, name="plan_item_edit"),
    path("planes/<int:plan_pk>/objetivo/<int:pk>/eliminar/", views.plan_item_delete, name="plan_item_delete"),
    path("planes/idiomas/test/<uuid:quiz_uuid>/", views.quiz_take, name="quiz_take"),
    path("planes/idiomas/test/<uuid:quiz_uuid>/resultado/", views.quiz_result, name="quiz_result"),

    path("circuitos/nuevo/", views.routine_create, name="routine_create"),
    path("circuitos/<int:pk>/editar/", views.routine_edit, name="routine_edit"),
    path("circuitos/<int:pk>/eliminar/", views.routine_delete, name="routine_delete"),
    path("estadisticas/", views.stats_list, name="stats_list"),
    path("estadisticas/<uuid:series_id>/", views.stats_detail, name="stats_detail"),
]
