"""
Django settings for todoapp project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# En local, si no defines DJANGO_SECRET_KEY, usa la clave insegura de siempre.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-^216q&g_0@lxmbe^7$myl6n4#vkl))!+d%su%&f-+nf8cir&*_",
)

# SECURITY WARNING: don't run with debug turned on in production!
# En local (sin la variable definida) sigue en True. En el hosting, la pondremos en "False".
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# En producción, define DJANGO_ALLOWED_HOSTS como "tuapp.up.railway.app,tudominio.com"
_hosts = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _hosts.split(",") if h.strip()]
if DEBUG:
    ALLOWED_HOSTS += ["localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in ALLOWED_HOSTS if h not in ("localhost", "127.0.0.1")]

# --------------------------------------------------------------
# CORS — para que la app móvil (Capacitor) pueda llamar a la API.
# --------------------------------------------------------------
# Capacitor no sirve la app desde tu dominio: en Android usa
# "https://localhost" y en iOS "capacitor://localhost" como origen. Para
# el navegador eso es un sitio DISTINTO al de tu servidor, así que sin
# esto todas las llamadas de la app fallarían por política de mismo
# origen — y el error que ves en consola no dice claramente el motivo.
CORS_ALLOWED_ORIGINS = [
    "https://localhost",
    "http://localhost",
    "capacitor://localhost",
    "ionic://localhost",
]
# Para poder abrir la app en el navegador del ordenador mientras la
# desarrollas, servida desde cualquier puerto local (npx serve, python
# -m http.server, live reload de Capacitor...). Sin esto tendrías que ir
# añadiendo el puerto a mano cada vez que cambia.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://localhost:\d+$",
    r"^https?://127\.0\.0\.1:\d+$",
    # Recarga en vivo desde el móvil: Capacitor sirve desde la IP de tu
    # ordenador en la red local (192.168.x.x o 10.x.x.x).
    r"^https?://192\.168\.\d+\.\d+:\d+$",
    r"^https?://10\.\d+\.\d+\.\d+:\d+$",
]
# Durante el desarrollo con recarga en vivo, Capacitor sirve desde la IP
# de tu ordenador en un puerto cualquiera. Añádelos aquí vía entorno,
# separados por comas, en vez de abrir CORS a todo el mundo.
_extra_cors = os.environ.get("EXTRA_CORS_ORIGINS", "")
CORS_ALLOWED_ORIGINS += [o.strip() for o in _extra_cors.split(",") if o.strip()]

# La API se autentica con la cabecera Authorization (Basic), no con
# cookies de sesión, así que no hace falta permitir credenciales.
CORS_ALLOW_CREDENTIALS = False

# Solo se aplica CORS bajo /api/ — el resto del sitio (la web normal) no
# necesita ni debe aceptar peticiones de otros orígenes.
CORS_URLS_REGEX = r"^/api/.*$"

# --------------------------------------------------------------
# CANDADO DE USUARIO/CONTRASEÑA (solo para ti)
# Define BASIC_AUTH_USER y BASIC_AUTH_PASSWORD como variables de
# entorno en el hosting para proteger TODA la app con un login
# simple tipo "ventana emergente" del navegador.
# Si no defines estas variables, el candado queda desactivado
# (útil en local, donde no hace falta).
# --------------------------------------------------------------
BASIC_AUTH_USER = os.environ.get("BASIC_AUTH_USER", "")
BASIC_AUTH_PASSWORD = os.environ.get("BASIC_AUTH_PASSWORD", "")


# --------------------------------------------------------------
# IA para generar planes (ver tasks/ai.py) — Google Gemini, porque tiene
# tier gratis permanente (sin tarjeta) con salida en JSON estructurado.
# Clave gratis en https://aistudio.google.com/apikey. Sin ella definida,
# el botón de "generar con IA" falla con un aviso legible en vez de
# reventar — el resto de la app funciona igual.
# --------------------------------------------------------------
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CorsMiddleware tiene que ir lo más arriba posible, y SIEMPRE por
    # encima de CommonMiddleware: si va por debajo, las respuestas de
    # redirección salen sin las cabeceras CORS y el navegador de la app
    # las bloquea sin decir por qué.
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'todoapp.basic_auth.BasicAuthMiddleware',
]

ROOT_URLCONF = 'todoapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'todoapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'  # aqui caen los archivos tras collectstatic

# En desarrollo, que WhiteNoise sirva directamente desde STATICFILES_DIRS
# en vez de desde el manifiesto compilado en STATIC_ROOT. Sin esto,
# cualquier cambio en un .js o .css no se veía hasta ejecutar
# `collectstatic` a mano — nada avisaba de que hiciera falta, así que un
# arreglo podía darse por probado y en realidad seguir sirviendo la
# versión vieja. En producción (DEBUG=False) sigue usando el manifiesto
# comprimido, que es lo que conviene ahí.
WHITENOISE_USE_FINDERS = DEBUG

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
