# Generated by Django 6.0.7 on 2026-07-21 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, help_text='Hora límite. Si pasa sin marcarla, se auto-marca como no hecha.', null=True)),
                ('repeat', models.CharField(choices=[('none', 'No se repite'), ('daily', 'Cada día'), ('weekly', 'Cada semana'), ('monthly', 'Cada mes'), ('yearly', 'Cada año'), ('custom', 'Personalizado')], default='none', max_length=10)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('custom_days', models.CharField(blank=True, max_length=20)),
                ('is_important', models.BooleanField(default=False)),
                ('series_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('series_start_date', models.DateField(blank=True, editable=False, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('expired', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['is_done', 'due_date', 'due_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('done', 'Hecho'), ('not_done', 'No hecho')], max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('auto_expired', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='tasks.task')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
