# Generated by Django 5.2.16 on 2026-08-14 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_aigenerationlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="language_name",
            field=models.CharField(
                blank=True,
                help_text="Solo con study_subtype='language': el idioma del curso, ej. 'francés'.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="level_from",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                    ("C2", "C2"),
                ],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="level_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                    ("C2", "C2"),
                ],
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="quiz_every_n_videos",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="study_subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("general", "Hábito simple"),
                    ("language", "Idioma (curso con vídeos por nivel)"),
                ],
                default="general",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="subcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("upper_body", "Tren superior"),
                    ("lower_body", "Tren inferior"),
                    ("running", "Running"),
                    ("reading", "Lectura"),
                    ("study_session", "Estudio"),
                    ("stretch", "Estiramientos"),
                    ("focus_other", "Otro"),
                    ("language", "Idiomas"),
                ],
                help_text="Deporte → qué entrenar. Enfoque → qué cronometrar. En el resto no se usa.",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Posición en el temario completo del curso.",
                    ),
                ),
                (
                    "scheduled_week",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="En qué semana del plan toca ver este vídeo.",
                        null=True,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        max_length=2,
                    ),
                ),
                ("youtube_video_id", models.CharField(max_length=32)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("channel_title", models.CharField(blank=True, max_length=200)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "has_captions",
                    models.BooleanField(
                        default=False,
                        help_text="Si YouTube reporta subtítulos disponibles — no garantiza que se puedan descargar (ver notas de tasks/youtube_search.py), pero ayuda a priorizar.",
                    ),
                ),
                (
                    "source_playlist_id",
                    models.CharField(
                        blank=True,
                        help_text="De qué playlist salió, para poder revisar la fuente.",
                        max_length=64,
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=200)),
                ("watched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_modules",
                        to="tasks.plan",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
