# Generated by Django 5.2.16 on 2026-08-14 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_study_language_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursePlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        help_text="Ej. 'francés'. En minúscula, sin acentos raros.",
                        max_length=40,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("A1", "A1"),
                            ("A2", "A2"),
                            ("B1", "B1"),
                            ("B2", "B2"),
                            ("C1", "C1"),
                            ("C2", "C2"),
                        ],
                        max_length=2,
                    ),
                ),
                ("youtube_playlist_id", models.CharField(max_length=64)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("channel_title", models.CharField(blank=True, max_length=200)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Por qué se eligió esta playlist, qué cubre, algo a vigilar...",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desactivar en vez de borrar si deja de estar disponible o resulta floja.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden dentro de su idioma+nivel, si hay varias.",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["language", "level", "order"],
            },
        ),
        migrations.RemoveField(
            model_name="coursemodule",
            name="source_playlist_id",
        ),
        migrations.AddField(
            model_name="coursemodule",
            name="source_playlist",
            field=models.ForeignKey(
                blank=True,
                help_text="De qué playlist curada salió, para poder revisar la fuente.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tasks.courseplaylist",
            ),
        ),
    ]
