# Generated by Django 5.2.16 on 2026-07-24 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.UUIDField(blank=True, null=True)),
                ('exercise', models.CharField(choices=[('pullup', 'Dominadas')], default='pullup', max_length=32)),
                ('total_reps', models.PositiveIntegerField(default=0)),
                ('session_duration_seconds', models.PositiveIntegerField(default=0)),
                ('avg_rep_seconds', models.FloatField(blank=True, null=True)),
                ('rest_alerts_triggered', models.PositiveIntegerField(default=0)),
                ('rep_durations', models.JSONField(blank=True, default=list)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_sessions', to='tasks.task')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
