# Generated by Django 5.2.16 on 2026-07-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_workoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='sets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='total_sets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
