# Generated by Django 5.2.16 on 2026-08-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_course_playlist_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="known_languages",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
