# Generated by Django 5.2.16 on 2026-08-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_plan_known_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="language_name",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="task",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A1", "A1"),
                    ("A2", "A2"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C1", "C1"),
                    ("C2", "C2"),
                ],
                max_length=2,
            ),
        ),
    ]
