# Generated by Django 5.2.16 on 2026-07-26 00:47
#
# NOTA: `makemigrations` detectó además dos cambios sueltos que ya venían de
# antes en el proyecto (sin relación con esto): un campo `last_result` en
# Task que quitaste del modelo pero cuya migración de borrado nunca se
# generó, y un desajuste AutoField -> BigAutoField por un cambio de versión
# de Django. Los he dejado fuera a propósito para no arrastrar cambios que
# no pediste (el primero borraría una columna con datos en producción).
# Si en algún momento quieres limpiarlos, se hace aparte y con calma.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_workoutsession_sets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('mode', models.CharField(choices=[('pose', 'Cámara (pose tracking)'), ('manual', 'Manual (reps a mano)'), ('timed', 'Cronometrado'), ('distance', 'Distancia (cardio)')], default='manual', max_length=16)),
                ('counter_key', models.CharField(blank=True, help_text="Qué contador de workout.js usar (solo aplica si mode='pose'). Ej: 'pullup'.", max_length=32)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Umbrales/ajustes propios de este ejercicio para el contador (opcional).')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
