# Generated by Django 5.2.16 on 2026-07-26 00:48
#
# Migra el "pullup" que hasta ahora vivía hardcodeado en
# WorkoutSession.EXERCISE_CHOICES a una fila real del catálogo Exercise.
# No toca WorkoutSession ni workout.js: es solo la semilla del catálogo,
# para poder engancharlo más adelante sin tener que crear nada a mano.

from django.db import migrations


def seed_pullup(apps, schema_editor):
    Exercise = apps.get_model("tasks", "Exercise")
    Exercise.objects.get_or_create(
        slug="pullup",
        defaults=dict(
            name="Dominadas",
            mode="pose",
            counter_key="pullup",
            config={},
            is_active=True,
            order=0,
        ),
    )


def remove_pullup(apps, schema_editor):
    Exercise = apps.get_model("tasks", "Exercise")
    Exercise.objects.filter(slug="pullup").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_exercise'),
    ]

    operations = [
        migrations.RunPython(seed_pullup, remove_pullup),
    ]
