# Generated by Django 5.2.16 on 2026-07-26 01:02
#
# Añade variantes de dominadas al catálogo. Todas comparten el mismo
# contador de cámara ("pullup" en workout.js) porque el movimiento base
# — colgarte y subir hasta que la nariz pase la barra — es el mismo; lo
# único que cambia es el agarre (ancho, supino en chin-ups) o si añades
# peso o impulso, y eso no afecta a cómo se detecta la repetición.
#
# "Dominadas con peso" de momento solo cuenta reps como las demás — el
# campo para anotar los kg del lastre es cosa del futuro WorkoutSet.

from django.db import migrations

VARIANTS = [
    dict(slug="wide-pullup", name="Dominadas anchas", order=1),
    dict(slug="chinup", name="Chin ups", order=2),
    dict(slug="weighted-pullup", name="Dominadas con peso", order=3),
    dict(slug="jumping-pullup", name="Dominadas con salto", order=4),
]


def seed_variants(apps, schema_editor):
    Exercise = apps.get_model("tasks", "Exercise")
    for v in VARIANTS:
        Exercise.objects.get_or_create(
            slug=v["slug"],
            defaults=dict(
                name=v["name"],
                mode="pose",
                counter_key="pullup",
                config={},
                is_active=True,
                order=v["order"],
            ),
        )


def remove_variants(apps, schema_editor):
    Exercise = apps.get_model("tasks", "Exercise")
    Exercise.objects.filter(slug__in=[v["slug"] for v in VARIANTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_seed_pullup_exercise'),
    ]

    operations = [
        migrations.RunPython(seed_variants, remove_variants),
    ]
