# Generated by Django 5.2.16 on 2026-07-26 01:15
#
# NOTA: como en la migración 0007, `makemigrations` sigue arrastrando el
# mismo ruido preexistente de siempre (RemoveField last_result, y el
# AutoField -> BigAutoField de occurrence/task). Se deja fuera otra vez a
# propósito, mismo motivo: no es parte de este cambio y tocar last_result
# borraría una columna con datos en producción sin que nadie lo haya pedido.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_add_pullup_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='body_area',
            field=models.CharField(blank=True, choices=[('upper_body', 'Tren superior'), ('lower_body', 'Tren inferior'), ('running', 'Running')], db_index=True, help_text='A qué subcategoría de Deporte pertenece (tren superior/inferior/running). Vacío = aparece en el selector pase lo que pase.', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('upper_body', 'Tren superior'), ('lower_body', 'Tren inferior'), ('running', 'Running')], help_text="Solo aplica si category='sport'. Filtra qué ejercicios se ofrecen al entrenar.", max_length=16),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='distance_km',
            field=models.FloatField(blank=True, help_text='Solo running: km recorridos.', null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='steps',
            field=models.PositiveIntegerField(blank=True, help_text='Solo running: pasos, si los tienes (cinta, reloj…).', null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='exercise',
            field=models.CharField(choices=[('pullup', 'Dominadas'), ('wide-pullup', 'Dominadas anchas'), ('chinup', 'Chin ups'), ('weighted-pullup', 'Dominadas con peso'), ('jumping-pullup', 'Dominadas con salto'), ('situp', 'Abdominales'), ('squat', 'Sentadillas'), ('running', 'Correr')], default='pullup', max_length=32),
        ),
    ]
