# Generated by Django 5.2.16 on 2026-07-26 01:16
#
# - Etiqueta las 5 dominadas ya sembradas como body_area='upper_body'.
# - Añade Abdominales y Sentadillas (lower_body): entran en el catálogo,
#   pero como counter_key no coincide con ningún contador de workout.js
#   todavía, el selector las enseña y al elegirlas avisa de que aún no
#   tienen seguimiento por cámara — en vez de romper o mentir.
# - Añade Correr (running, mode=distance): esta sí queda operativa ya,
#   por formulario manual (cinta, reloj, Samsung Health…), no cámara.

from django.db import migrations

UPPER_BODY_SLUGS = ["pullup", "wide-pullup", "chinup", "weighted-pullup", "jumping-pullup"]

NEW_EXERCISES = [
    dict(slug="situp", name="Abdominales", mode="pose", counter_key="situp",
         body_area="lower_body", order=5),
    dict(slug="squat", name="Sentadillas", mode="pose", counter_key="squat",
         body_area="lower_body", order=6),
    dict(slug="running", name="Correr", mode="distance", counter_key="",
         body_area="running", order=7),
]


def seed(apps, schema_editor):
    Exercise = apps.get_model("tasks", "Exercise")

    Exercise.objects.filter(slug__in=UPPER_BODY_SLUGS).update(body_area="upper_body")

    for e in NEW_EXERCISES:
        Exercise.objects.get_or_create(
            slug=e["slug"],
            defaults=dict(
                name=e["name"], mode=e["mode"], counter_key=e["counter_key"],
                body_area=e["body_area"], config={}, is_active=True, order=e["order"],
            ),
        )


def unseed(apps, schema_editor):
    Exercise = apps.get_model("tasks", "Exercise")
    Exercise.objects.filter(slug__in=[e["slug"] for e in NEW_EXERCISES]).delete()
    Exercise.objects.filter(slug__in=UPPER_BODY_SLUGS).update(body_area="")


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_subcategories'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
