# Generated by Django 5.2.16 on 2026-07-26 02:19
#
# Como en 0007/0010, se deja fuera a propósito el ruido preexistente
# (RemoveField last_result, AutoField -> BigAutoField). Esta vez SÍ se va
# a limpiar, pero en su propia migración (0014, tarea 4 de la sesión) para
# no mezclarlo con el campo user.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_seed_lower_body_and_running'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Dueño de la ocurrencia. Ver Task.user para el mismo criterio.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Dueño de la tarea. Hoy siempre es el usuario por defecto (ver tasks/utils.py:get_current_user) — preparado para cuando haya login real.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Dueño de la sesión. Ver Task.user para el mismo criterio.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
