# Generated by Django 5.2.16 on 2026-07-26 02:20
#
# Crea (si no existe) el usuario por defecto que usa tasks/utils.py:
# get_current_user(), y le asigna todas las filas de Task/WorkoutSession/
# Occurrence que se quedaron con user=NULL al añadir el campo en 0012.
# Idempotente: correrla dos veces no crea usuarios duplicados ni pisa
# filas que ya tuvieran user asignado. Reversible: al revertir, vuelve a
# dejar en NULL solo las filas que esta migración tocó (no borra el
# usuario, por si en el ínterin se le colgó algo más).

from django.db import migrations

DEFAULT_USERNAME = "default"


def backfill(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Task = apps.get_model("tasks", "Task")
    WorkoutSession = apps.get_model("tasks", "WorkoutSession")
    Occurrence = apps.get_model("tasks", "Occurrence")

    user, _ = User.objects.get_or_create(
        username=DEFAULT_USERNAME,
        defaults={"is_active": True},
    )

    Task.objects.filter(user__isnull=True).update(user=user)
    WorkoutSession.objects.filter(user__isnull=True).update(user=user)
    Occurrence.objects.filter(user__isnull=True).update(user=user)


def unbackfill(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Task = apps.get_model("tasks", "Task")
    WorkoutSession = apps.get_model("tasks", "WorkoutSession")
    Occurrence = apps.get_model("tasks", "Occurrence")

    user = User.objects.filter(username=DEFAULT_USERNAME).first()
    if not user:
        return

    Task.objects.filter(user=user).update(user=None)
    WorkoutSession.objects.filter(user=user).update(user=None)
    Occurrence.objects.filter(user=user).update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_user_fields'),
    ]

    operations = [
        migrations.RunPython(backfill, unbackfill),
    ]
