# Generated by Django 5.2.16 on 2026-07-26 02:21
#
# Ruido preexistente (last_result, AutoField->BigAutoField) fuera otra vez,
# se limpia en 0015 (tarea 4), no aquí.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_backfill_default_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='added_weight_kg',
            field=models.FloatField(blank=True, help_text='Peso extra usado (ej. chaleco lastrado en dominadas con peso). No lo mide la cámara, se anota a mano.', null=True),
        ),
    ]
