# Generated by Django 5.2.16 on 2026-07-27 00:46
#
# Tarea 3: quita choices=EXERCISE_CHOICES de WorkoutSession.exercise (era la
# lista duplicada que había que sincronizar a mano con la tabla Exercise).
# El ruido preexistente (last_result, AutoField->BigAutoField) se limpia en
# 0016 (tarea 4), no aquí.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_workoutsession_added_weight_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='exercise',
            field=models.CharField(default='pullup', max_length=32),
        ),
    ]
