# Generated by Django 5.2.16 on 2026-07-27 00:47
#
# Tarea 4: limpia el ruido preexistente que las migraciones 0007/0010/0012/
# 0014/0015 venían excluyendo a propósito.
# - RemoveField last_result: el campo ya no existe en el modelo desde hace
#   tiempo, solo faltaba generar su migración de borrado. Comprobado antes
#   de esto que las 5 filas de Task en db.sqlite3 lo tenían vacío — no se
#   pierde ningún dato real.
# - AutoField -> BigAutoField en Occurrence/Task: alinea con
#   DEFAULT_AUTO_FIELD (settings.py), que cambió en algún momento de
#   versión de Django. Solo metadata, incluso en SQLite no cambia
#   comportamiento real de los IDs.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_workoutsession_exercise_no_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='last_result',
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
