# Generated by Django 5.2.16 on 2026-07-27 01:11
#
# Añade los ejercicios cronometrados de abdominales (mode="timed", sin
# contador de cámara — se hacen a tiempo, no a reps) y un "meta ejercicio"
# ab-circuit que representa "hiciste un circuito completo" (es el valor
# que se guarda en WorkoutSession.exercise cuando terminas una Routine).
# También crea una rutina por defecto ya montada y en un orden pensado
# como haría un entrenador: plancha (activa el core sin fatigar todavía),
# crunch y elevación de piernas (abdomen, dos ángulos distintos),
# bicicleta (oblicuos), mountain climbers (sube pulsaciones), y superman
# de cierre para trabajar la zona lumbar y no descompensar solo con
# flexión abdominal.

from django.db import migrations

AB_EXERCISES = [
    dict(slug="plank", name="Plancha", order=8),
    dict(slug="crunch", name="Crunch", order=9),
    dict(slug="leg-raise", name="Elevación de piernas", order=10),
    dict(slug="bicycle-crunch", name="Bicicleta", order=11),
    dict(slug="mountain-climber", name="Mountain climbers", order=12),
    dict(slug="superman", name="Superman", order=13),
]

META_EXERCISE = dict(slug="ab-circuit", name="Circuito de abdominales", order=14)

DEFAULT_ROUTINE_NAME = "Abdominales completo"
DEFAULT_ROUTINE_ORDER = [
    "plank", "crunch", "leg-raise", "bicycle-crunch", "mountain-climber", "superman",
]


def seed(apps, schema_editor):
    Exercise = apps.get_model("tasks", "Exercise")
    Routine = apps.get_model("tasks", "Routine")
    RoutineItem = apps.get_model("tasks", "RoutineItem")
    User = apps.get_model("auth", "User")

    for e in AB_EXERCISES:
        Exercise.objects.get_or_create(
            slug=e["slug"],
            defaults=dict(
                name=e["name"], mode="timed", counter_key="",
                body_area="lower_body", config={}, is_active=True, order=e["order"],
            ),
        )
    Exercise.objects.get_or_create(
        slug=META_EXERCISE["slug"],
        defaults=dict(
            name=META_EXERCISE["name"], mode="timed", counter_key="",
            body_area="lower_body", config={}, is_active=True, order=META_EXERCISE["order"],
        ),
    )

    user, _ = User.objects.get_or_create(username="default", defaults={"is_active": True})

    routine, created = Routine.objects.get_or_create(
        name=DEFAULT_ROUTINE_NAME,
        user=user,
        defaults=dict(subcategory="lower_body", default_work_seconds=40, default_rest_seconds=20),
    )
    if created:
        for i, slug in enumerate(DEFAULT_ROUTINE_ORDER):
            ex = Exercise.objects.get(slug=slug)
            RoutineItem.objects.create(routine=routine, exercise=ex, order=i)


def unseed(apps, schema_editor):
    Exercise = apps.get_model("tasks", "Exercise")
    Routine = apps.get_model("tasks", "Routine")

    Routine.objects.filter(name=DEFAULT_ROUTINE_NAME).delete()  # cascada a sus RoutineItem
    slugs = [e["slug"] for e in AB_EXERCISES] + [META_EXERCISE["slug"]]
    Exercise.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_routine_workoutsession_routine_routineitem'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
