# Generated by Django 5.2.16 on 2026-07-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_seed_ab_circuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_avoid',
            field=models.BooleanField(default=False, help_text='Antitarea: el objetivo es NO hacerlo (ej. "no fumar"). Si no marcas nada antes de la hora límite, cuenta como éxito — silencio es que lo evitaste. Solo hace falta tocar algo si caes.'),
        ),
    ]
