# Generated by Django 5.2.16 on 2026-07-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_task_is_avoid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_avoid',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('study', 'Estudio'), ('sport', 'Deporte'), ('work', 'Trabajo'), ('personal', 'Personal'), ('other', 'Otro'), ('avoid', 'Antitarea')], db_index=True, default='general', help_text='Tipo de tarea. Define qué extras tendrá disponibles (timer, pose tracking, etc).', max_length=16),
        ),
    ]
