# Generated by Django 5.2.16 on 2026-07-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_occurrence_unique_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineitem',
            name='target_reps',
            field=models.PositiveIntegerField(default=8, help_text='Solo para ejercicios de cámara: repeticiones por serie.'),
        ),
        migrations.AddField(
            model_name='routineitem',
            name='target_sets',
            field=models.PositiveIntegerField(default=3, help_text='Solo para ejercicios de cámara: series objetivo.'),
        ),
    ]
