# Generated by Django 5.2.16 on 2026-07-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_routineitem_target_reps_routineitem_target_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reopened_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo devolviste la tarea a pendientes a mano. Sirve para que el barrido automático no vuelva a cerrarla en el acto.', null=True),
        ),
    ]
