# Generated by Django 5.2.16 on 2026-07-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_task_reopened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='avoid_fail_label',
            field=models.CharField(blank=True, help_text='Antitareas: texto del botón para "he caído". En blanco usa "He caído".', max_length=32),
        ),
        migrations.AddField(
            model_name='task',
            name='avoid_question',
            field=models.CharField(blank=True, help_text='Antitareas: la pregunta de la notificación. En blanco usa "¿Has caído hoy?".', max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='avoid_success_label',
            field=models.CharField(blank=True, help_text='Antitareas: texto del botón de la notificación para "lo he evitado". En blanco usa "No he caído".', max_length=32),
        ),
    ]
