# Generated by Django 5.2.17 on 2026-09-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_warmupstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='watch_keyword',
            field=models.CharField(blank=True, help_text="Solo para 'Curso de Udemy': palabra o frase que debe aparecer en el título de la pestaña de Udemy para contar el tiempo en esta tarea.", max_length=120),
        ),
        migrations.AlterField(
            model_name='task',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('upper_body', 'Tren superior'), ('lower_body', 'Tren inferior'), ('running', 'Running'), ('reading', 'Lectura'), ('study_session', 'Estudio'), ('stretch', 'Estiramientos'), ('focus_other', 'Otro'), ('language', 'Idiomas'), ('udemy', 'Curso de Udemy')], help_text='Deporte → qué entrenar. Enfoque → qué cronometrar. En el resto no se usa.', max_length=16),
        ),
        migrations.AlterField(
            model_name='timersession',
            name='app_package',
            field=models.CharField(blank=True, help_text='Paquete Android de la app leída (ej. com.adobe.reader) si source=app_usage, o el dominio vigilado (ej. udemy.com) si source=pc_usage.', max_length=120),
        ),
        migrations.AlterField(
            model_name='timersession',
            name='source',
            field=models.CharField(choices=[('manual', 'Cronómetro manual'), ('app_usage', 'Tiempo en la app'), ('pc_usage', 'Tiempo en el PC')], default='manual', max_length=16),
        ),
    ]
