# Generated by Django 5.2.16 on 2026-07-29 00:19

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_swap_mountain_climber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='target_reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='target_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='target_sets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='avoid_fail_label',
            field=models.CharField(blank=True, help_text='Antitareas: texto del botón para "he caído". En blanco usa "Romper racha".', max_length=32),
        ),
        migrations.AlterField(
            model_name='task',
            name='avoid_success_label',
            field=models.CharField(blank=True, help_text='Antitareas: texto del botón de la notificación para "lo he evitado". En blanco usa "Sigo con la racha".', max_length=32),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('started_on', models.DateField(default=datetime.date.today)),
                ('weeks', models.PositiveIntegerField(default=12, help_text='Duración prevista. 12 semanas por defecto (12 Week Year).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-started_on'],
            },
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Plan al que contaba esta sesión, si había uno activo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_sessions', to='tasks.plan'),
        ),
        migrations.CreateModel(
            name='PlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sets', models.PositiveIntegerField(default=3)),
                ('start_reps', models.PositiveIntegerField(default=8)),
                ('start_seconds', models.PositiveIntegerField(default=40, help_text='Para ejercicios cronometrados, en vez de repeticiones.')),
                ('reps_increment', models.PositiveIntegerField(default=1, help_text='Cuánto sube cada escalón.')),
                ('sessions_per_step', models.PositiveIntegerField(default=2, help_text='Cada cuántas sesiones se sube un escalón.')),
                ('max_reps', models.PositiveIntegerField(blank=True, help_text='Tope opcional: al llegar aquí deja de subir.', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='tasks.plan')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'exercise'), name='unique_exercise_per_plan')],
            },
        ),
    ]
