# Generated by Django 5.2.17 on 2026-09-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_task_watch_keyword_alter_task_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitem',
            name='watch_keyword',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='course_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
