# Generated by Django 5.2.16 on 2026-07-29 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_workoutsession_target_reps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.UUIDField(blank=True, help_text='Para objetivos de tarea (estudiar, no fumar). Es la serie de la tarea.', null=True)),
                ('label', models.CharField(blank=True, help_text='Cómo llamarlo. En blanco usa el nombre del ejercicio o la tarea.', max_length=80)),
                ('progression', models.CharField(choices=[('completion', 'Cumplimiento (objetivo fijo)'), ('reps', 'Repeticiones (sube hasta un techo)'), ('double', 'Doble (repeticiones y luego peso)')], default='reps', max_length=12)),
                ('start_sets', models.PositiveIntegerField(default=3)),
                ('start_reps', models.PositiveIntegerField(default=8)),
                ('start_seconds', models.PositiveIntegerField(default=40)),
                ('start_weight_kg', models.FloatField(default=0)),
                ('goal_sets', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_weight_kg', models.FloatField(blank=True, null=True)),
                ('sessions_per_step', models.PositiveIntegerField(default=2, help_text='Cada cuántas sesiones cumplidas se sube un escalón.')),
                ('reps_increment', models.PositiveIntegerField(default=1)),
                ('weight_increment_kg', models.FloatField(default=2.5, help_text='Solo en progresión doble: cuánto peso se añade al completar el rango.')),
                ('rep_range_low', models.PositiveIntegerField(default=6, help_text='Solo en progresión doble: a cuántas repeticiones se vuelve al subir peso.')),
                ('deload_after_failures', models.PositiveIntegerField(default=3, help_text='Tras estas sesiones seguidas sin llegar al objetivo, se baja un escalón. 0 lo desactiva.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(blank=True, help_text='Para objetivos de ejercicio.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.plan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='PlanExercise',
        ),
    ]
