# Generated by Django 5.2.17 on 2026-09-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_planitem_watch_keyword_task_course_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='body_area',
            field=models.CharField(blank=True, choices=[('upper_body', 'Tren superior'), ('lower_body', 'Tren inferior'), ('running', 'Running'), ('warmup', 'Estiramientos y calentamientos')], db_index=True, help_text='A qué subcategoría de Deporte pertenece (tren superior/inferior/running). Vacío = aparece en el selector pase lo que pase.', max_length=16),
        ),
        migrations.AlterField(
            model_name='routine',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('upper_body', 'Tren superior'), ('lower_body', 'Tren inferior'), ('running', 'Running'), ('warmup', 'Estiramientos y calentamientos')], help_text='Para poder ofrecer esta rutina desde el selector de esa subcategoría de Deporte.', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('upper_body', 'Tren superior'), ('lower_body', 'Tren inferior'), ('running', 'Running'), ('warmup', 'Estiramientos y calentamientos'), ('reading', 'Lectura'), ('study_session', 'Estudio'), ('stretch', 'Estiramientos'), ('focus_other', 'Otro'), ('language', 'Idiomas'), ('udemy', 'Curso de Udemy')], help_text='Deporte → qué entrenar. Enfoque → qué cronometrar. En el resto no se usa.', max_length=16),
        ),
    ]
