# Generated by Django 5.2.16 on 2026-07-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_planitem_delete_planexercise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planitem',
            options={'ordering': ['-is_headline', 'order']},
        ),
        migrations.AddField(
            model_name='planitem',
            name='is_headline',
            field=models.BooleanField(default=False, help_text='La medida que define si el plan se ha conseguido. "Estar en forma" no se puede medir; "4x12 con 20 kg" sí — esa es la prueba de que vas hacia el objetivo. El resto de ejercicios son el camino, progresan pero no deciden.'),
        ),
    ]
