# Generated by Django 5.2.16 on 2026-07-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_planitem_options_planitem_is_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='custom_days',
            field=models.CharField(blank=True, default='0,2,4', help_text='Días de la semana, como en las tareas. Por defecto lunes, miércoles y viernes.', max_length=20),
        ),
        migrations.AddField(
            model_name='plan',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='repeat',
            field=models.CharField(default='custom', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='task_series_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
