# Generated by Django 5.2.16 on 2026-08-04 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_add_dips'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Objetivo en minutos para tareas de Enfoque (category='work'). Ej. 60 para 'leer una hora'.", null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('study', 'Estudio'), ('sport', 'Deporte'), ('work', 'Enfoque'), ('personal', 'Personal'), ('other', 'Otro'), ('avoid', 'Antitarea')], db_index=True, default='general', help_text='Tipo de tarea. Define qué extras tendrá disponibles (timer, pose tracking, etc).', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('upper_body', 'Tren superior'), ('lower_body', 'Tren inferior'), ('running', 'Running'), ('reading', 'Lectura'), ('study_session', 'Estudio'), ('stretch', 'Estiramientos'), ('focus_other', 'Otro')], help_text='Deporte → qué entrenar. Enfoque → qué cronometrar. En el resto no se usa.', max_length=16),
        ),
        migrations.CreateModel(
            name='TimerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.UUIDField(blank=True, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Cronómetro manual'), ('app_usage', 'Tiempo en la app')], default='manual', max_length=16)),
                ('app_package', models.CharField(blank=True, help_text='Paquete Android de la app leída (ej. com.adobe.reader). Solo si source=app_usage.', max_length=120)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('target_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, help_text='Para cuando esta tarea cuente para un objetivo del 12 Week Year. Sin usar todavía.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timer_sessions', to='tasks.plan')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timer_sessions', to='tasks.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timer_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
