# Generated by Django 5.2.16 on 2026-08-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_task_target_minutes_alter_task_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text="ID o URL de un vídeo de YouTube (ej. 'dQw4w9WgXcQ' o el enlace completo — se limpia solo al guardar). Si está puesto, esta tarea NO pasa por el selector de ejercicios ni por el temporizador: al darle a play se va directa al vídeo embebido, y al terminar se marca como hecha ella sola. Streaming en directo: no se descarga ni se guarda nada.", max_length=255),
        ),
    ]
