# Generated by Django 5.2.16 on 2026-08-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_task_target_minutes_alter_task_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_filename',
            field=models.CharField(blank=True, help_text="Solo para mode='timed'. Nombre del archivo de vídeo (ej. 'abdominales.mp4') que debe existir en el móvil, en la carpeta privada de la app (Android/data/com.libreta.tareas/files/circuitos-videos/ — se sube por ADB, no hay descarga desde la app). Si está puesto, el circuito reproduce el vídeo en vez de una cuenta atrás en blanco, y el paso dura lo que dure el vídeo.", max_length=255),
        ),
    ]
