# Generated by Django 5.2.16 on 2026-08-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_savedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='reward',
            field=models.CharField(blank=True, help_text='La recompensa que te prometes al empezar el ciclo (opcional). Se enseña en la pantalla de cierre si la has puesto.', max_length=200),
        ),
    ]
