# Generated by Django 5.2.16 on 2026-08-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_plan_closed_at_plan_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='final_progress_pct',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='reward',
            field=models.CharField(blank=True, help_text='La recompensa que te prometes al empezar el ciclo (opcional). Se enseña en la pantalla de cierre si la has puesto — y solo si el plan llega al umbral de completado.', max_length=200),
        ),
    ]
