# Generated by Django 5.2.16 on 2026-08-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_plan_final_progress_pct_alter_plan_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_video_count',
            field=models.PositiveIntegerField(blank=True, help_text='Solo con youtube_playlist_id: cuántos vídeos de la lista hay que ver para dar la tarea por hecha (ej. 5). Si no se pone y tampoco hay target_minutes, se da por hecha al terminar 1 vídeo de la lista.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='youtube_playlist_id',
            field=models.CharField(blank=True, help_text='Alternativa a youtube_video_id: ID o URL de una playlist de YouTube (el trozo list=... del enlace). Junto con target_minutes o target_video_count decide cuándo se da por vista.', max_length=255),
        ),
    ]
