# Generated by Django 5.2.16 on 2026-08-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_exercise_video_filename'),
        ('tasks', '0037_task_target_video_count_task_youtube_playlist_id'),
    ]

    operations = [
    ]
