# Generated by Django 5.2.16 on 2026-08-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_task_target_video_count_task_youtube_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='has_local_video',
            field=models.BooleanField(default=False, help_text="Alternativa a youtube_video_id: el vídeo es un archivo del propio dispositivo (elegido con el selector nativo), no de YouTube. El archivo en sí NO vive aquí — cada aparato guarda el suyo por su cuenta (IndexedDB en la web, el plugin nativo en la app), este campo solo le dice al servidor 'esta tarea se resuelve con un vídeo local' para que workout_kind la trate como 'video' igual que si tuviera uno de YouTube. Solo para category='sport'/'work' — Estudio no lo usa."),
        ),
    ]
