# Generated by Django 5.2.16 on 2026-08-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_merge_20260807_1524'),
        ('tasks', '0038_task_has_local_video'),
    ]

    operations = [
    ]
