# Generated by Django 5.2.16 on 2026-08-08 14:38
#
# Escrita a mano a partir de lo que generó makemigrations, quitando un
# cambio que no tiene nada que ver con esto (un RemoveField de
# exercise.video_filename — ese campo ya existía en la base de datos
# desde antes, migrations.py no lo tiene en el modelo, pero no es cosa
# de esta migración tocarlo).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_merge_20260808_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='wants_timer',
            field=models.BooleanField(default=False, help_text="Solo para category='general': activa el botón de cronómetro/vídeo en la lista, en vez de ser una tarea normal de marcar y ya. General/Estudio/Enfoque comparten el mismo temporizador (TimerSession) — esto solo decide si General lo ofrece o no; Estudio y Enfoque ya lo ofrecen siempre, por categoría."),
        ),
        migrations.AlterField(
            model_name='task',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('upper_body', 'Tren superior'), ('lower_body', 'Tren inferior'), ('running', 'Running'), ('reading', 'Lectura'), ('stretch', 'Estiramientos'), ('focus_other', 'Otro')], help_text='Deporte → qué entrenar. Enfoque → qué cronometrar. En el resto no se usa.', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_minutes',
            field=models.PositiveIntegerField(blank=True, help_text="Objetivo en minutos para tareas de Enfoque o Estudio (category='work'/'study'). Ej. 60 para 'leer una hora'. En blanco = sesión libre, sin objetivo que cumplir.", null=True),
        ),
    ]
