# Generated by hand (no working Django env over the device bridge to run
# makemigrations) — mirrors exactly what `makemigrations` would produce for
# the choices changes in Task.category and Task.subcategory: "Personal" y
# "Otro" quitados de category (cero tareas reales en ninguna de las dos),
# "Enfoque" renombrado a "Lectura", y "Estudio"/"Estiramientos"/"Otro"
# quitados de subcategory dentro de esa categoría (cero tareas reales con
# ninguno de los tres). Solo toca los choices — ninguna fila cambia de
# valor, así que no hace falta tocar datos.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0048_add_hip_forward_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('study', 'Estudio'), ('sport', 'Deporte'), ('work', 'Lectura'), ('avoid', 'Antitarea')], db_index=True, default='general', help_text='Tipo de tarea. Define qué extras tendrá disponibles (timer, pose tracking, etc).', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('upper_body', 'Tren superior'), ('lower_body', 'Tren inferior'), ('running', 'Running'), ('warmup', 'Estiramientos y calentamientos'), ('reading', 'Lectura'), ('language', 'Idiomas'), ('udemy', 'Curso de Udemy')], help_text='Deporte → qué entrenar. Enfoque → qué cronometrar. En el resto no se usa.', max_length=16),
        ),
    ]
