# Generated by Django 5.2.17 on 2026-09-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0050_set_voice_step_fast_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='is_warmup_bookend',
            field=models.BooleanField(default=False, help_text='Usar este circuito como calentamiento/estiramiento antes y después de las sesiones de esta subcategoría, en vez del vídeo genérico.'),
        ),
    ]
