# Generated by Django 5.2.17 on 2026-09-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0053_task_playlist_videos_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='playlist_start_index',
            field=models.PositiveIntegerField(blank=True, help_text='Solo con youtube_playlist_id: en qué posición de la lista (0 = el primero) hay que empezar a reproducir hoy, para no volver siempre al principio de la playlist. Lo mantienen al día tanto Plan.sync_task() (objetivos de Plan) como _spawn_next() (tareas sueltas repetidas), usando playlist_videos_cache de abajo. En blanco = empezar por el principio (playlist sin seguimiento, o recién puesta).', null=True),
        ),
    ]
