# Generated by Django 5.2.17 on 2026-09-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0054_alter_task_playlist_start_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planitem',
            options={'ordering': ['-is_headline', 'order', 'pk']},
        ),
        migrations.AlterField(
            model_name='planitem',
            name='progression',
            field=models.CharField(choices=[('completion', 'Cumplimiento (objetivo fijo)'), ('reps', 'Repeticiones (sube hasta un techo)'), ('double', 'Doble (repeticiones y luego peso)'), ('distance', 'Distancia (running: sube km y baja ritmo)'), ('failure', 'Al fallo (series sin objetivo de repeticiones)')], default='reps', max_length=12),
        ),
    ]
