# Generated by Django 5.2.17 on 2026-09-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0055_alter_planitem_options_alter_planitem_progression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitem',
            name='progression',
            field=models.CharField(choices=[('completion', 'Cumplimiento (objetivo fijo)'), ('reps', 'Repeticiones (sube hasta un techo; con peso objetivo, sube peso por ciclos)'), ('distance', 'Distancia (running: sube km y baja ritmo)'), ('failure', 'Al fallo (series sin objetivo de repeticiones)')], default='reps', max_length=12),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='rep_range_low',
            field=models.PositiveIntegerField(default=6, help_text='Solo en repeticiones con peso objetivo puesto: a cuántas repeticiones se vuelve al subir peso.'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='weight_increment_kg',
            field=models.FloatField(default=2.5, help_text='Solo si hay peso objetivo puesto (reps o al fallo, en un ejercicio con peso): cuánto se añade al completar el rango/ciclo.'),
        ),
    ]
