# Generated by Django 5.2.17 on 2026-09-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0056_alter_planitem_progression_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reading_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Se pone al llegar de verdad a reading_last_page — señal de que el plan se cerró (repeat pasa a REPEAT_NONE), distinta de is_done.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reading_current_page",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Solo reading_mode='plan': última página reportada por el visor de PDF (ver record_reading_page) — mismo patrón que playlist_start_index, pero de página en vez de vídeo. Se arrastra de un día al siguiente vía _spawn_next, nunca se reinicia sola.",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reading_final_pct",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="% guardado al terminar el plan: 100 si se llegó a tiempo o antes, menos si se tardó de más — ver record_reading_page para la fórmula exacta (plazo previsto ÷ tiempo real).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reading_last_page",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Solo reading_mode='plan': última página real del contenido (excluye glosario/apéndices) — cuándo se considera terminado el libro de verdad, y con qué se compara reading_current_page.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reading_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("freestyle", "Freestyle (cronómetro / extensión)"),
                    ("plan", "Plan de lectura (visor propio con página)"),
                ],
                default="freestyle",
                help_text="Solo Lectura: 'freestyle' (cronómetro/extensión, de toda la vida) o 'plan' (visor de PDF propio con seguimiento de página).",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reading_pdf_key",
            field=models.CharField(
                blank=True,
                help_text="Solo reading_mode='plan': clave para encontrar el archivo del PDF guardado en IndexedDB en ESTE navegador — se genera al elegir el archivo (ver reading_plan_form.html) y no cambia aunque se reelija el PDF, para que el visor lo siga encontrando.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reading_started_on",
            field=models.DateField(
                blank=True,
                help_text="Solo reading_mode='plan': fecha en que se creó el plan — con reading_target_weeks fija el plazo, y con la fecha real de finalización decide reading_final_pct si se termina tarde.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reading_target_weeks",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Solo reading_mode='plan': en cuántas semanas se quiere terminar el libro. Con reading_last_page y reading_current_page decide el ritmo (páginas/día) que enseña el visor — ver reading_plan_status. El plan NO se cierra solo al pasar este plazo, sigue hasta la página real.",
                null=True,
            ),
        ),
    ]
