# Generated by Django 5.2.17 on 2026-09-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0059_debuglog_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="course_progress_pct",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
