# Generated by hand to match models.py (sandbox no puede correr manage.py
# makemigrations sobre el mount del navegador -- mismo formato que las
# generadas automáticamente).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0060_udemy_course_progress_pct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="reading_pdf_key",
            field=models.CharField(
                blank=True,
                help_text="Solo reading_mode='plan': clave para encontrar el archivo del PDF guardado en IndexedDB en ESTE navegador — se genera al elegir el archivo (ver reading_plan_form.html) y no cambia aunque se reelija el PDF, para que el visor lo siga encontrando.",
                max_length=64,
            ),
        ),
    ]
