# Generated by hand to match models.py (sandbox no puede correr manage.py
# makemigrations sobre el mount del navegador -- mismo formato que las
# generadas automáticamente).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0061_alter_task_reading_pdf_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reading_progress_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Solo reading_mode='plan': cuándo se guardó por última vez "
                           "reading_current_page — referencia para topar cuánto puede "
                           "avanzar de golpe en un solo aviso del visor (ver "
                           "record_reading_page). Sin esto, arrastrar la barra de scroll "
                           "o pasar rapidísimo por encima de todas las páginas hasta el "
                           "final del archivo se guardaba igual que haberlo leído entero.",
            ),
        ),
    ]
