# Generated by hand to match models.py (sandbox no puede correr manage.py
# makemigrations sobre el mount del navegador -- mismo formato que las
# generadas automáticamente).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0062_task_reading_progress_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reading_first_page",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Solo reading_mode='plan': página real donde empieza el contenido, "
                           "después de portada/índice/prólogo... Con esto el ritmo y el % leído "
                           "(ver reading_plan_status) se calculan sobre las páginas de contenido "
                           "de verdad, no desde la 1 -- y el visor abre aquí la primera vez que "
                           "se abre el libro, en vez de en la portada. 1 por defecto (el libro "
                           "empieza al principio del archivo, como si no se hubiera puesto nada).",
            ),
        ),
    ]
