# Generated by hand to match models.py (sandbox no puede correr manage.py
# makemigrations sobre el mount del navegador -- mismo formato que las
# generadas automáticamente).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0063_task_reading_first_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reading_day_start_page",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Solo reading_mode='plan': reading_current_page en el momento en que "
                           "se generó ESTA instancia diaria (ver _spawn_next) -- punto de partida "
                           "para medir cuánto se ha leído hoy en concreto (ver reading_today_status), "
                           "ya que reading_current_page es acumulado de todo el libro y no se reinicia.",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reading_day_goal",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                help_text="Solo reading_mode='plan': páginas que tocaba leer HOY para ir al ritmo, "
                           "fijadas una sola vez al generarse esta instancia diaria (ver "
                           "_reading_day_goal_for) y nunca recalculadas mientras se lee -- así "
                           "reading_today_status puede pasar de 100% si se lee de más, en vez de "
                           "recortarse como reading_plan_status. None si todavía no se ha calculado "
                           "(instancias de antes de que existiera este campo -- ver "
                           "ensure_reading_day_goal).",
            ),
        ),
    ]
