# Generated by Django 5.2.17 on 2026-09-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0078_add_watch_requires_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitem',
            name='weekly_linear',
            field=models.BooleanField(default=False, help_text="Reparte el objetivo linealmente entre las semanas del plan (de partida a destino, a partes iguales) en vez de subir por ciclos con incremento manual. Solo aplica a 'repeticiones' y 'al fallo'. Por defecto en objetivos nuevos (plan_item_form/plan_item_bulk_form); los antiguos se quedan en False para no cambiarles el objetivo de un día para otro."),
        ),
    ]
