# Añade el campo Exercise.level (Principiante/Intermedio/Avanzado), pedido
# por Alex para poder generar planes de deporte automáticamente por nivel
# en el futuro. Solo esquema (AddField) -- los valores por ejercicio y el
# nuevo ejercicio "Dominadas anchas con peso" se rellenan en
# 0085_set_exercise_levels.py, la siguiente migración.
#
# Generated by Django 5.2.17 on 2026-09-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0083_add_handstand_pushup'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], db_index=True, help_text='Para generar planes de deporte automáticamente por nivel. Vacío = calentamiento/estiramientos (no entran en la selección por nivel) o running (nivel propio, no aplica).', max_length=12),
        ),
    ]
