# Generated by hand to match models.py (sandbox no puede correr manage.py
# makemigrations sobre el mount del navegador -- mismo formato que las
# generadas automáticamente, ver 0064).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0085_set_exercise_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reading_day_baseline_date",
            field=models.DateField(
                blank=True,
                null=True,
                help_text="Solo reading_mode='plan': de qué día de calendario son "
                           "reading_day_start_page/reading_day_goal ahora mismo -- se rellenaba "
                           "asumiendo que solo se leía en el due_date de la instancia (ver "
                           "_spawn_next), pero el visor se puede abrir cualquier día desde "
                           "Planes (ver reading_session_ready). Sin este campo, leer 'adelantado' "
                           "un día que no tocaba dejaba esas páginas contando para el objetivo "
                           "del día que sí tocaba en cuanto llegaba. ensure_reading_day_goal "
                           "compara esto con hoy en cada apertura del visor y, si no coincide, "
                           "reinicia el punto de partida a la página actual -- cada día de "
                           "calendario acaba con su propio tramo, se haya leído el día que tocaba "
                           "o de más.",
            ),
        ),
    ]
