# Generated by Django 5.2.17 on 2026-09-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0086_task_reading_day_baseline_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reading_pending_seconds',
            field=models.PositiveIntegerField(default=0, help_text="Solo reading_mode='plan': tiempo real de lectura ya medido (ver record_reading_page) pero todavía sin volcar a un TimerSession — se vacía en _flush_reading_time (Terminar sesión de hoy, o al terminar el libro). Sin esto, el Plan de lectura no dejaba ningún minuto en ningún sitio y 'Tiempo acumulado' (tasks/time_stats.py) no tenía nada que sumar de Lectura salvo el cronómetro suelto."),
        ),
        migrations.AddField(
            model_name='task',
            name='reading_time_anchor_at',
            field=models.DateTimeField(blank=True, help_text="Solo reading_mode='plan': última vez que record_reading_page midió un hueco de tiempo real, aparte de reading_progress_at (que solo se mueve cuando la página avanza de verdad, y no sirve para esto: reutilizarlo recontaría el mismo hueco dos veces en un aviso que no avanza página) — se actualiza en CADA aviso, avance o no.", null=True),
        ),
    ]
