# Generated by Django 5.2.17 on 2026-10-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0093_occurrence_completion_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitem',
            name='watch_site',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('upper_body', 'Tren superior'), ('lower_body', 'Tren inferior'), ('running', 'Running'), ('warmup', 'Estiramientos y calentamientos'), ('reading', 'Lectura'), ('language', 'Idiomas'), ('udemy', 'Curso de Udemy'), ('ilerna', 'Clases de Ilerna (Zoom)')], help_text='Deporte → qué entrenar. Enfoque → qué cronometrar. En el resto no se usa.', max_length=16),
        ),
    ]
